language: python
matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8
cache:
    pip: true
before_install: 
  - pip install pip --upgrade
  - pip install codecov
after_success:
  - codecov
