version: 2.1

orbs:
  python: circleci/python@0.3.2
python:
  version: 3.5.1

jobs:
  build-docker:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      # build the application image
      - run: docker build -t opt_app .
      - run: docker run -d -p 127.0.0.1:80:80 --name opt_app opt_app
      - run: docker ps | grep -q opt_app
workflows:
  main:
    jobs:
      - build-docker
