defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

#inst_conda_bld: &inst_conda_bld
#  - run: conda config --add channels conda-forge
#  - run: conda config --set always_yes true
#  - run: conda config --set quiet true
#  - run: conda install conda-build

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: apt-get install -y python-tables
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: which pip
      - run: conda install scipy;
      - run: conda install numpy;
      - run: conda install numba;
      - run: conda install dask;
      - run: pip install git+https://github.com/russelljjarvis/jit_hub.git@neuronunit
      - run: pip install tables
      - run: pip install pip --upgrade; pip install -r requirements.txt;
      - run: pip install -e .
      - run: echo "REDO 2"
      - run: pip install git+https://github.com/russelljjarvis/neuronunit
      - run: python unittest/latest_file_adexp.py


  test:
    <<: *defaults
    parallelism: 1
    environment:
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 1
      PYEMMA_NJOBS: 1

    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y python-tables
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: conda install conda-build
      - run: conda install scipy;
      - run: pip install git+https://github.com/russelljjarvis/jit_hub.git@neuronunit
      - run: pip install tables
      - run: pip install git+https://github.com/russelljjarvis/neuronunit
      - run: apt-get update
      - run: pip install pip --upgrade; pip install -r requirements.txt;
      - run: pip install -e .
      - run: python unittest/latest_file_adexp.py
