version: 2.1

orbs:
  python: circleci/python@0.3.2
python:
  version: 3.5.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - run:
          command: sudo pip install pip --upgrade; sudo pip install -r requirements.txt;
          name: install
      - run:
          name: numba
          command: sudo sudo pip install git+https://github.com/russelljjarvis/jit_hub.git;
      - run:
          name: more
          command: sudo python setup.py install;

workflows:
  main:
    jobs:
      - build-and-test
